# Generated by Django 3.1.3 on 2020-11-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=20)),
                ('cus_uname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
